definitions:
  dto.CreateRoleDTO:
    properties:
      descripcion:
        type: string
      nombre_rol:
        type: string
    required:
    - descripcion
    - nombre_rol
    type: object
  models.Role:
    properties:
      descripcion:
        type: string
      nombre_rol:
        type: string
    type: object
info:
  contact: {}
paths:
  /roles:
    get:
      description: Retrieve a list of all roles in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Role'
            type: array
      summary: List all roles
      tags:
      - roles
    post:
      consumes:
      - application/json
      description: Adds a new role to the system
      parameters:
      - description: Role data
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/dto.CreateRoleDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new role
      tags:
      - roles
  /roles/{id}:
    delete:
      description: Remove a role by its ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a role
      tags:
      - roles
    get:
      description: Retrieve a single role by its ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Role'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a role by ID
      tags:
      - roles
    put:
      consumes:
      - application/json
      description: Update the information of an existing role
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated role data
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/dto.CreateRoleDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Role'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a role
      tags:
      - roles
swagger: "2.0"
